find_path(SDL2_TTF_INCLUDE_DIR SDL_ttf.h PATH_SUFFIXES SDL2)
find_library(SDL2_TTF_LIBRARY SDL2_ttf)

add_library(SDL2::SDL2_ttf SHARED IMPORTED)
set_target_properties(SDL2::SDL2_ttf PROPERTIES
	INTERFACE_INCLUDE_DIRECTORIES "${SDL2_TTF_INCLUDE_DIR}"
	IMPORTED_LOCATION "${SDL2_TTF_LIBRARY}"
)
