find_path(SDL2_NET_INCLUDE_DIR SDL_net.h PATH_SUFFIXES SDL2)
find_library(SDL2_NET_LIBRARY SDL2_net)

add_library(SDL2::SDL2_net SHARED IMPORTED)
set_target_properties(SDL2::SDL2_net PROPERTIES
	INTERFACE_INCLUDE_DIRECTORIES "${SDL2_NET_INCLUDE_DIR}"
	IMPORTED_LOCATION "${SDL2_NET_LIBRARY}"
)
