find_path(SDL2_MIXER_INCLUDE_DIR SDL_mixer.h PATH_SUFFIXES SDL2)
find_library(SDL2_MIXER_LIBRARY SDL2_mixer)

add_library(SDL2::SDL2_mixer SHARED IMPORTED)
set_target_properties(SDL2::SDL2_mixer PROPERTIES
	INTERFACE_INCLUDE_DIRECTORIES "${SDL2_MIXER_INCLUDE_DIR}"
	IMPORTED_LOCATION "${SDL2_MIXER_LIBRARY}"
)
